baseURL = 'https://northaugustabarbell.github.io/'
languageCode = 'en-us'
title = 'North Augusta Barbell'
theme = 'nab-dark'

[params]
subtitle = 'Home of Olympic Weightlifting in the CSRA'
address = '1764 Knox Ave. North Augusta, SC'
hours = '<div class="hours-row"><div class="column-1">Monday-Saturday:</div><div class="column-2">5am â€“ 10pm</div></div><div class="hours-row"><div class="column-1">Sunday:</div><div class="column-2">Closed</div></div>'
phone = '704-577-6049'
email = 'NorthAugustaBarbell@gmail.com'
copyright = '2025 North Augusta Barbell'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Staff'
    pageRef = '/staff'
    weight = 20

  [[menus.main]]
    name = 'About Us'
    pageRef = '/about'
    weight = 30
  
  [[menus.main]]
    name = 'Join Now'
    url= 'https://docs.google.com/forms/d/e/1FAIpQLSdb1Y_M-5t3L9Cx78L3DGC0pFtluvfP_Ruodo2IWcmf6GIFqw/viewform?usp=pp_url'
    weight = 40

[caches]
  [caches.images]
    dir = ':cacheDir/images'
